USE [master]
GO

/****** Object:  Database [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF]    Script Date: 13.12.2022 00:35:26 ******/
CREATE DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Oteldb', FILENAME = N'C:\Users\senaa\Documents\Oteldb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Oteldb_log', FILENAME = N'C:\Users\senaa\Documents\Oteldb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ARITHABORT OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET  DISABLE_BROKER 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET  MULTI_USER 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET DB_CHAINING OFF 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET QUERY_STORE = OFF
GO

USE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [C:\USERS\SENAA\DOCUMENTS\OTELDB.MDF] SET  READ_WRITE 
GO

